//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostingInstructionsApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ClientVendors
    {
        public int ClientVenderId { get; set; }
        public int ClientId { get; set; }
        public int VendorId { get; set; }
        public string ClientName { get; set; }
        public string ClientCode { get; set; }
        public string VendorName { get; set; }
        public string SourceName { get; set; }
    }
}
